repos:
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.2

  - repo: local
    hooks:
      - id: cargo fmt
        name: cargo fmt
        entry: cargo fmt
        language: system
        pass_filenames: false
        types: [rust]
      - id: cargo check
        name: cargo check
        entry: cargo check
        language: system
        pass_filenames: false
        types: [rust]
      - id: cargo clippy
        name: cargo clippy
        entry: cargo clippy --all-targets -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]
